### ISSUE TITLE
Null Pointer Exception 

### ISSUE THREAD

**Issue by bwkchee** [mebbert/VariantToolChest#1]
Every time I run a set operation either with --compare or out1=i[fId1:fID2] I get a null pointer exception like the following:

Intersect type: het_homo_alt
Complement type: het_homo_alt
log4j:WARN No appenders could be found for logger (vtc.datastructures.VariantPool).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Parsed variants: 270,000
Performing intersect...
Added 2,600 variant records to intersection.
Printing intermediate file for intersect
java.lang.NullPointerException
    at org.broadinstitute.variant.variantcontext.writer.IndexingVariantContextWriter.setIndexSequenceDictionary(IndexingVariantContextWriter.java:144)
    at org.broadinstitute.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:99)
    at org.broadinstitute.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:190)
    at vtc.datastructures.VariantPool.printVariantPoolToVCF(VariantPool.java:808)
    at vtc.datastructures.VariantPool.printVariantPool(VariantPool.java:732)
    at vtc.tools.setoperator.SetOperatorEngine.performOperations(SetOperatorEngine.java:467)
    at vtc.tools.setoperator.SetOperatorEngine.performComparison(SetOperatorEngine.java:344)
    at vtc.tools.setoperator.SetOperatorEngine.operate(SetOperatorEngine.java:271)
    at vtc.VTCEngine.main(VTCEngine.java:65)

**Comment by mebbert** [comment]
Thank you for the feedback. Can you tell me which release you downloaded? I just posted a new .jar yesterday. The most updated version will generally be available by cloning the repository.

Thanks!

**Comment by bwkchee** [comment]
I've tried the 0.9-alpha.jar, 0.9.1-alph.jar and also building from scratch all resulting in the null pointer exception.  It doesn't look like there have been any changes to the repository or releases in ~25 days?

**Comment by mebbert** [comment]
Odd. How big are your files? Can you send them to me along with your exact command? We'll try to fix it asap.

Send to me.mark@gmail.com

**Comment by bwkchee** [comment]
Hi Mark,

```
 Thanks for helping to troubleshoot.  Below is the commands and the
```

output.  I'm not attaching hg1.fa since it's really big

java -Xmx4g -jar vtc-0.9.1-alpha.jar SetOperator -i
SRR766061_trimmed_samtools.vcf SRR766061_trimmed_partek.vcf -R ../hg19.fa
--compare

Intersect type: het_homo_alt

Complement type: het_homo_alt

2015-04-20 12:02:04 INFO  VariantPool:619 - Parsing
SRR766061_trimmed_samtools.vcf ...

2015-04-20 12:02:04 INFO  VariantPool:619 - Parsing
SRR766061_trimmed_partek.vcf ...

Performing intersect...

Printing intermediate file for intersect

2015-04-20 12:02:04 ERROR SetOperatorEngine:294 - Caught unexpected
exception, something is very wrong!

java.lang.NullPointerException

at
org.broadinstitute.variant.variantcontext.writer.IndexingVariantContextWriter.setIndexSequenceDictionary(IndexingVariantContextWriter.java:144)

at
org.broadinstitute.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:99)

at
org.broadinstitute.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:190)

at
vtc.datastructures.VariantPool.printVariantPoolToVCF(VariantPool.java:808)

at vtc.datastructures.VariantPool.printVariantPool(VariantPool.java:732)

at
vtc.tools.setoperator.SetOperatorEngine.performOperations(SetOperatorEngine.java:467)

at
vtc.tools.setoperator.SetOperatorEngine.performComparison(SetOperatorEngine.java:344)

at
vtc.tools.setoperator.SetOperatorEngine.operate(SetOperatorEngine.java:271)

at vtc.VTCEngine.main(VTCEngine.java:65)

Thanks,
Brant

**Comment by mebbert** [comment]
Thanks Brant. Did you attach the VCFs? I don't see them.

**Comment by mebbert** [comment]
Hey Brant, can you attach the VCFs or email them to me?

**Comment by mebbert** [comment]
Brant, we were able to determine the cause. Looks like your reference genome is missing the necessary dictionary file (<ref_name>.dict). You can create this file using Picard's CreateSequenceDictionary.jar. Let me know if this doesn't resolve the issue. I also just pushed a change that will alert the user if the .dict file is missing.
