### ISSUE TITLE
VCFv4.2 is not a supported version

### ISSUE THREAD

**Issue by hackerzone85** [mebbert/VariantToolChest#3]
``` javascript
$ java -jar VariantToolChest-0.9-SNAPSHOT-jar-with-dependencies.jar VarStats -i /home/blab/Desktop/matK/samtool_result/matK.raw.vcf -s T
2015-07-02 18:50:25 INFO  VarStatsEngine:91 - Namespace(SUMMARY=T, association=false, VCF=[/home/blab/Desktop/matK/samtool_result/matK.raw.vcf], OUTPUT=null, pheno=null, DETAILED=null)
2015-07-02 18:50:25 INFO  AbstractVariantPool:134 - Opening /home/blab/Desktop/matK/samtool_result/matK.raw.vcf for reading...
2015-07-02 18:50:25 ERROR VarStatsEngine:184 - Caught unexpected exception, something is very wrong!
org.broad.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: VCFv4.2 is not a supported version, for input source: /home/blab/Desktop/matK/samtool_result/matK.raw.vcf
    at org.broad.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:127)
    at org.broad.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:81)
    at org.broad.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:69)
    at vtc.datastructures.AbstractVariantPool.openVCFForReading(AbstractVariantPool.java:135)
    at vtc.datastructures.AbstractVariantPool.getNextVar(AbstractVariantPool.java:196)
    at vtc.tools.varstats.VariantPoolSummarizer.summarizeVariantPool(VariantPoolSummarizer.java:212)
    at vtc.tools.varstats.VariantPoolSummarizer.summarizeVariantPools(VariantPoolSummarizer.java:177)
    at vtc.tools.varstats.VarStatsEngine.doStats(VarStatsEngine.java:146)
    at vtc.VTCEngine.main(VTCEngine.java:66)
Caused by: org.broad.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: VCFv4.2 is not a supported version
    at org.broadinstitute.variant.vcf.VCFCodec.readHeader(VCFCodec.java:91)
    at org.broad.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:73)
    at org.broad.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:125)
    ... 8 more
```

**Comment by mwadswor** [comment]
Thanks for reporting this issue. We are working on upgrading our dependencies and will push the changes soon.

Thanks,
Mark

**Comment by emmaielle** [comment]
Is there an update on this? I want to use VCFs with 4.2 version too.
Thanks,
Moira

**Comment by mebbert** [comment]
I apologize for the delay. I just pushed a new release that should allow VCF v4.2. Please let us know if you have any trouble!
